### ISSUE TITLE
Suggestion: Default all volume sliders to 50% when generating new players.cfg files

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#172] opened 2022-05-29 01:37 UTC
See title. Default volume of 100% for each of effects, music, and message is very loud. 50% seems like it would make sense as a default. Low priority, but would be a good QoL change.

Should apply to generating both new players.cfg files and players_MODNAME.cfg files (when launching the game without one already existing).

**Comment by rafalh** [comment] 2024-03-16 14:47
Duplicate of #116

**Closed by rafalh** 2024-03-16 14:47 UTC
